# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:

    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [1]:
import numpy as np
np.random.seed(seed=1)

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. Comment on the type of its elements.

In [4]:
# 1.1) Initialize my_array1
list1= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
my_array1 = np.array(list1)

# Print shape and data type of my_array1
print(f"Shape of my_array1: {my_array1.shape}")
print(f"Type of elements in my_array1: {my_array1.dtype}")

# 1.2) Initialize my_array2
list2= [0, 1, "a", "hehehhe", 4, 5, 6, "mamma_mia", 8, 9]
my_array2 = np.array(list2)

# Print shape and data type of my_array1
print(f"Shape of my_array2: {my_array2.shape}")
print(f"Type of elements in my_array2: {my_array2.dtype}")

# The array type is <U21 which means Python converted all elements into that string type
# The conversion to <U21 makes everything uniform but has limited numerical uses

Shape of my_array1: (10,)
Type of elements in my_array1: int64
Shape of my_array2: (10,)
Type of elements in my_array2: <U21


---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [9]:
# 2) Initialize homogenous my_array3
list3= [[0, 1, 2, 3, 4, 5], [44, 789, 23, 6, 86, 0]]
my_array3 = np.array(list3)

# Print shape, size, and data type of my_array3
print(f"Shape of my_array3: {my_array3.shape}")
print(f"Size of my_array3: {my_array3.size}")
print(f"Type of elements in my_array3: {my_array3.dtype}")
# Size represents the total number of elements in an array irrespective of the dimensions of the array

Shape of my_array3: (2, 6)
Size of my_array3: 12
Type of elements in my_array3: int64


---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features. 

Print the shape of the array.

In [16]:
# already defined first and second inputs
num_samples = 100
num_features = 17

# YOUR CODE HERE
tabular_data = np.random.random((num_samples, num_features))

# Print shape of tabular_data
print(f"Shape of tabular_data: {tabular_data.shape}")

Size of tabular_data: (100, 17)


---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [17]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

# YOUR CODE HERE
image_data = np.random.random((num_images, num_rows, num_cols, num_channels))

# Print shape of tabular_data
print(f"Shape of image_data: {image_data.shape}")

Shape of image_data: (100, 256, 256, 3)


---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over elements in the array. Print the output.

In [50]:
# YOUR CODE HERE

#Initialize 3x2 array
list4= [[0, 1, 2, 3, 4, 5], [44, 789, 23, 6, 86, 0], [23, 641, 243, 246, 534,777]]
my_array4 = np.array(list4)

# Print shape of my_array4
print(f"Shape of my_array4: {my_array4.shape}")

# Print sum of all elements
print(f"Sum of all elements: {np.sum(my_array4)}")

# Print sum of all elements by columns
print(f"Sum of all elements by column: {np.sum(my_array4, axis=0)}")

# Print sum of all elements by row and change the type of the resulting array elements to float
print(f"Sum of all elements by row: {np.sum(my_array4, axis=1).astype(float)}")

# Print first row of array
print(f"First row of array: {my_array4[0, :]}")

# Print second row of array
print(f"Second row of array: {my_array4[1, :]}")

# Select the element at position (1, 0)
print(f"Select the element at position (1, 0): {my_array4[1, 0]}")

# Modify the element at position (2, 1) by setting its value to 10 and print the array again
my_array4[2,1] = 10
print(f"Modify the element at position (2, 1) by setting its value to 10 and print the array again: {my_array4[2, 1]}")

# Loop over elements in the array. Print the output.
for i in range(my_array4.shape[0]):
    for j in range(my_array4.shape[1]):
        print(f"Element at position ({i}, {j}) is {my_array4[i, j]}")

Shape of my_array4: (3, 6)
Sum of all elements: 3427
Sum of all elements by column: [  67 1431  268  255  624  782]
Sum of all elements by row: [  15.  948. 2464.]
First row of array: [0 1 2 3 4 5]
Second row of array: [ 44 789  23   6  86   0]
Select the element at position (1, 0): 44
Modify the element at position (2, 1) by setting its value to 10 and print the array again: 10
Element at position (0, 0) is 0
Element at position (0, 1) is 1
Element at position (0, 2) is 2
Element at position (0, 3) is 3
Element at position (0, 4) is 4
Element at position (0, 5) is 5
Element at position (1, 0) is 44
Element at position (1, 1) is 789
Element at position (1, 2) is 23
Element at position (1, 3) is 6
Element at position (1, 4) is 86
Element at position (1, 5) is 0
Element at position (2, 0) is 23
Element at position (2, 1) is 10
Element at position (2, 2) is 243
Element at position (2, 3) is 246
Element at position (2, 4) is 534
Element at position (2, 5) is 777


You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) numpy array of zeros
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [62]:
# YOUR CODE HERE

# 1) Create and print a (3,2) numpy array of pixel values between 0 and 1.
pixel_array = np.random.random((3, 2))
print(f"3x2 array of pixel values between 0 and 1:\n{pixel_array}")

# 2) Create and print a (27,) numpy array representing years from 1991 to 2017
years_array = np.arange(1991, 2018)
print(f"\nArray representing years from 1991 to 2017:\n{years_array}")

# 3) Create and print a (3, 5, 10) numpy array of zeros
zero_array = np.zeros((3,5,10))
print(f"\n(3, 5, 10) numpy array of zeros:\n{zero_array}")

# 4) Create and print a (3, 5, 10) numpy array of ones
ones_array = np.ones((3,5,10))
print(f"\n(3, 5, 10) numpy array of ones:\n{ones_array}")

# 5) Create and print an array with a constant value (let's say 5) using np.ones()
fives_array = np.ones((3,5,10))*5
print(f"\n(3, 5, 10) numpy array of fives\n{fives_array}")

# 6) Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.
normal_array = np.random.normal(0,1,10)
print(f"\nArray with random numbers from a normal distribution (mean 0, std 1):\n{normal_array}")

3x2 array of pixel values between 0 and 1:
[[0.67512814 0.05833417]
 [0.88433504 0.70844905]
 [0.03160391 0.8382055 ]]

Array representing years from 1991 to 2017:
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]

(3, 5, 10) numpy array of zeros:
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]

(3, 5, 10) numpy array of ones:
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [64]:
years = np.arange(1991, 2018, 1)
print(years.shape)

(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d;
2. Convert the years_3d array to a flat 1D array. Call this array years_1d;
3. Add a new axis (in front) to the years_1d array. Call this array years_2d;
4. Remove the first axis from years_2d array. Call this array years_1d.

For each exercise print the array and its shape.

In [81]:
# YOUR CODE HERE

# 1) Create 3 nested arrays, each of size (3, 3). Call this array years_3d;
years_3d = years.reshape((3, 3, 3))
print(f"***Operation 1***\n3D array of years (years_3d):\n{years_3d}")
print(f"\nShape of 3D array of years (years_3d):{years_3d.shape}")

# 2) Convert the years_3d array to a flat 1D array. Call this array years_1d;
years_1d = years_3d.flatten()
print(f"\n***Operation 2***\nFlattened 1D array (years_1d):\n{years_1d}")
print(f"\nShape of flattened 1D array (years_1d):{years_1d.shape}")

# 3) Add a new axis (in front) to the years_1d array. Call this array years_2d;
years_2d = years_1d[np.newaxis, :]
print(f"\n***Operation 3***\n2D array with new axis in front(years_2d):\n{years_2d}")
print(f"\nShape of 2D array with new axis in front(years_2d):{years_2d.shape}")

# 3) Remove the first axis from years_2d array. Call this array years_1d.
years_1d = np.squeeze(years_2d)
print(f"\n***Operation 4***\n1D array with front axis removed (years_1d):\n{years_1d}")
print(f"\nShape of 1D array with front axis removed (years_1d):{years_1d.shape}")

***Operation 1***
3D array of years (years_3d):
[[[1991 1992 1993]
  [1994 1995 1996]
  [1997 1998 1999]]

 [[2000 2001 2002]
  [2003 2004 2005]
  [2006 2007 2008]]

 [[2009 2010 2011]
  [2012 2013 2014]
  [2015 2016 2017]]]

Shape of 3D array of years (years_3d):(3, 3, 3)

***Operation 2***
Flattened 1D array (years_1d):
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]

Shape of flattened 1D array (years_1d):(27,)

***Operation 3***
2D array with new axis in front(years_2d):
[[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
  2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]]

Shape of 2D array with new axis in front(years_2d):(1, 27)

***Operation 4***
1D array with front axis removed (years_1d):
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]

Shape of 1D array with fro

---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [99]:
# YOUR CODE HERE

import numpy as np

# Create two 2D integer arrays 'a' and 'b'
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# Ex. 1 Concatenate 'a' and 'b' along the first axis (vertically)
arr_1 = np.concatenate((a, b))
print(f"Ex. 1: Concatenating 'a' and 'b' vertically:\n{arr_1}\n")

# Ex. 2 Concatenate 'a' and 'b' along the first axis (vertically), but reversing the order
arr_2 = np.concatenate((b, a))
print(f"Ex. 2: Concatenating 'b' and 'a' vertically (reversed order):\n{arr_2}\n")

# Create two 2D string arrays 'a' and 'b'
a = np.array([["bb", "a"], ["fgh67", "terhug"]])
b = np.array([["ehbfer", "fhu43"]])

# Ex. 3 Concatenate 'a' and 'b' along the first axis (vertically)
arr_3 = np.concatenate((a, b))
print(f"Ex. 3: Concatenating string arrays 'a' and 'b' vertically:\n{arr_3}\n")

# Ex. 4 Concatenate 'b' and 'a' along the first axis (vertically), but reversing the order
arr_4 = np.concatenate((b, a))
print(f"Ex. 4: Concatenating string arrays 'b' and 'a' vertically (reversed order):\n{arr_4}\n")

# Create two 1D integer arrays 'a' and 'b'
a = np.array([1, 2])
b = np.array([5, 6])

# Ex. 5 Stack 'a' and 'b' vertically to create a 2D array
arr_5 = np.stack((a, b))
print(f"Ex. 5: Stacking 'a' and 'b' vertically to form a 2D array:\n{arr_5}\n")

# Ex. 6 Stack 'a' and 'b' horizontally to create a 2D array
arr_6 = np.stack((a, b), axis=1)
print(f"Ex. 6: Stacking 'a' and 'b' horizontally to form a 2D array:\n{arr_6}\n")

# Create two 2D integer arrays 'a' and 'b'
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Ex. 7 Stack 'a' and 'b' along the last axis (creating a 3D array)
arr_7 = np.stack((a, b), axis=-1)
print(f"Ex. 7: Stacking 'a' and 'b' along the last axis (creating a 3D array):\n{arr_7}\n")

# Ex. 8 Stack 'a' and 'b' along the first axis (creating a 3D array)
arr_8 = np.stack((a, b), axis=0)
print(f"Ex. 8: Stacking 'a' and 'b' along the first axis (creating a 3D array):\n{arr_8}\n")

Ex. 1: Concatenating 'a' and 'b' vertically:
[[1 2]
 [3 4]
 [5 6]]

Ex. 2: Concatenating 'b' and 'a' vertically (reversed order):
[[5 6]
 [1 2]
 [3 4]]

Ex. 3: Concatenating string arrays 'a' and 'b' vertically:
[['bb' 'a']
 ['fgh67' 'terhug']
 ['ehbfer' 'fhu43']]

Ex. 4: Concatenating string arrays 'b' and 'a' vertically (reversed order):
[['ehbfer' 'fhu43']
 ['bb' 'a']
 ['fgh67' 'terhug']]

Ex. 5: Stacking 'a' and 'b' vertically to form a 2D array:
[[1 2]
 [5 6]]

Ex. 6: Stacking 'a' and 'b' horizontally to form a 2D array:
[[1 5]
 [2 6]]

Ex. 7: Stacking 'a' and 'b' along the last axis (creating a 3D array):
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]

Ex. 8: Stacking 'a' and 'b' along the first axis (creating a 3D array):
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]



---
#### <span style="color:chocolate">Numpy broadcasting</span> 

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [82]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])

In [83]:
# adding a scalar
years + 2

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [84]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

Array a: [0 1 2]
Array b: [0 1 2]
Sum of a and b: [0 2 4]


In [85]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

Array a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b: [0 1 2]

Sum of a and b: [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [100]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

my_array shape:  (10, 4)


array([[0.17570345, 0.30260207, 0.06580329, 0.88611332],
       [0.69979914, 0.08792672, 0.29223849, 0.83994739],
       [0.77018785, 0.633768  , 0.59914193, 0.93710767],
       [0.58916931, 0.01857738, 0.81493963, 0.0999022 ],
       [0.97972572, 0.84550635, 0.4556143 , 0.24327394],
       [0.22992653, 0.26088887, 0.63883091, 0.70883718],
       [0.3522388 , 0.0377845 , 0.74929995, 0.47100049],
       [0.03872695, 0.23194054, 0.56470709, 0.06048921],
       [0.7651935 , 0.15181471, 0.19521509, 0.52815816],
       [0.49674863, 0.18707097, 0.76869568, 0.35771188]])

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [110]:
# YOUR CODE HERE

# Compute the mean and standard deviation for each column
column_means = np.mean(my_array, axis=0, keepdims=True)
column_stds = np.std(my_array, axis=0, keepdims=True)

print(f"Mean of each column:\n{column_means}")
print(f"Standard deviation of each column:\n{column_stds}")

# Standardize the array
standardized_array = (my_array - column_means) / column_stds

# Print the standardized array and its shape
print(f"\nStandardized array:\n{standardized_array}")
print(f"\nShape of standardized array: {standardized_array.shape}")

Mean of each column:
[[0.50974199 0.27578801 0.51444864 0.51325414]]
Standard deviation of each column:
[[0.28863685 0.25237416 0.24316515 0.3063663 ]]

Standardized array:
[[-1.15729689  0.10624726 -1.84502324  1.21703717]
 [ 0.65846461 -0.74437609 -0.91382398  1.0663485 ]
 [ 0.9023306   1.41844945  0.34829536  1.38348611]
 [ 0.2751808  -1.01916389  1.23574861 -1.34920827]
 [ 1.62828733  2.25743528 -0.24195216 -0.88123337]
 [-0.96943773 -0.05903594  0.51151359  0.63839606]
 [-0.54567942 -0.94305816  0.96580994 -0.13791873]
 [-1.63186035 -0.17373994  0.20668444 -1.47785489]
 [ 0.88502735 -0.49122817 -1.31282609  0.04864771]
 [-0.04501629 -0.3515298   1.04557354 -0.5077003 ]]

Shape of standardized array: (10, 4)


----
#### <span style="color:chocolate">Additional practice question</span> (not graded)

Consider the following image:

In [ ]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by removing:
    * the first and the last two rows, and
    * the first and the last two columns;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.

In [ ]:
# YOUR CODE HERE